name: Pipe line

on: [push]

env:
    APPLICATION_NAME: app2

jobs:
    lint:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4

            - name: Setup python
              uses: actions/setup-python@v5.1.1
            
            - name: Install requirements
              run: pip install --quiet --requirement requirements.txt
            
            - name: Lint code
              run: |
                flake8 --ignore=E501,E231,W1514,R1732 *.py
                pylint --disable=C0301 *.py
            
            - name: Run unit tests
              run: python -m unittest --verbose --failfast
              
