name: Pipe line

on: [push]

env:
  APPLICATION_NAME: app2

jobs:
    lint:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v4

            - name: Setup python
              uses: actions/setup-python@v5.1.1
              with:
                  python-version: 3.6
            
            - name: Install requirements
              run: pip install --quiet --requirement requirements.txt
            
            - name: Lint code
              run: |
                flake8 --ignore=E501,E231,W1514,R1732 *.py
                pylint --disable=C0301 *.py
            
            - name: Run unit tests
              run: python -m unittest --verbose --failfast
              
    
    build-docker-image:
        needs: [lint]
        runs-on: ubuntu-18.04
        steps:

            - uses: actions/checkout@v4

            - name: build docker image
              run: |
                docker build -t "${{ env.APPLICATION_NAME }}:latest"
                docker image save "${{ env.APPLICATION_NAME }}:latest" -o app2.image
            
            - name: list files
              run: ls -la

            - name: Upload a Docker image
              uses: actions/upload-artifact@v4.3.4
              with:
                name: app2.image
                path: ./app2.image
                    
    test-docker-image:
        needs: [lint, build-docker-image]
        runs-on: ubuntu-18.04
        steps:
            # - uses: actions/checkout@v4
        
            - name: Download docker image
              uses: actions/download-artifact@v4.1.8
              with:
                name: app2.image
            
            - name: list files
              run: ls -la
            
            - name: test image
              run: docker run app2.image -m unittest --verbose --failfast